### ISSUE TITLE
Implement FAB to bottomsheet with 2 buttons (QR scanning, Document Scanning)

### ISSUE THREAD

**Issue by antailbaxt3r** [Devsoc-BPGC/scanf-app#2]
![image](https://user-images.githubusercontent.com/42549114/88924393-d7734200-d290-11ea-8b4b-459258817977.png)

This is kind of what the bottom-sheet should look like

**Comment by Adithya2907** [comment]
I'd like to do this.

**Comment by antailbaxt3r** [comment]
> I'd like to do this.
Go ahead!
